INSERT INTO teachers (teacherID, name, specialist) VALUES
(1, 'John Doe', 'Mathematics Teacher'),
(2, 'Jane Smith', 'English Teacher'),
(3, 'Michael Johnson', 'Science Teacher'),
(4, 'Sarah Williams', 'History Teacher'),
(5, 'David Brown', 'Physical Education Teacher'),
(6, 'Emily Davis', 'Art Teacher'),
(7, 'Robert Wilson', 'Music Teacher'),
(8, 'Lisa Taylor', 'Computer Science Teacher'),
(9, 'James Anderson', 'Physics Teacher'),
(10, 'Michelle Martinez', 'Spanish Teacher'),
(11, 'Christopher Thompson', 'Biology Teacher'),
(12, 'Amanda Clark', 'Chemistry Teacher'),
(13, 'Richard Rodriguez', 'Geography Teacher'),
(14, 'Samantha Lee', 'Drama Teacher'),
(15, 'Matthew Young', 'Mathematics Teacher'),
(16, 'Stephanie Lewis', 'English Teacher'),
(17, 'Andrew Turner', 'Science Teacher'),
(18, 'Jennifer Hall', 'History Teacher'),
(19, 'Thomas Wright', 'Physical Education Teacher'),
(20, 'Karen Hernandez', 'Art Teacher'),
(21, 'Steven Scott', 'Music Teacher'),
(22, 'Melissa Phillips', 'Computer Science Teacher'),
(23, 'Charles Adams', 'Physics Teacher'),
(24, 'Rebecca Torres', 'Spanish Teacher'),
(25, 'Joseph Baker', 'Biology Teacher'),
(26, 'Amy Green', 'Chemistry Teacher'),
(27, 'Daniel Lewis', 'Geography Teacher'),
(28, 'Ashley Hill', 'Drama Teacher'),
(29, 'Patrick King', 'Mathematics Teacher'),
(30, 'Katherine Morgan', 'English Teacher'),
(31, 'Jonathan Allen', 'Science Teacher'),
(32, 'Lauren Roberts', 'History Teacher'),
(33, 'Brandon Turner', 'Physical Education Teacher'),
(34, 'Elizabeth White', 'Art Teacher'),
(35, 'Joshua Hall', 'Music Teacher'),
(36, 'Natalie Long', 'Computer Science Teacher'),
(37, 'Aaron Jackson', 'Physics Teacher'),
(38, 'Amy Collins', 'Spanish Teacher'),
(39, 'Justin Reed', 'Biology Teacher'),
(40, 'Brittany Hughes', 'Chemistry Teacher'),
(41, 'Ryan Murphy', 'Geography Teacher'),
(42, 'Christina Carter', 'Drama Teacher'),
(43, 'Timothy Adams', 'Mathematics Teacher'),
(44, 'Amanda Martin', 'English Teacher'),
(45, 'David Parker', 'Science Teacher'),
(46, 'Megan Turner', 'History Teacher'),
(47, 'Richard Wood', 'Physical Education Teacher'),
(48, 'Kimberly Ward', 'Art Teacher'),
(49, 'Christopher Perez', 'Music Teacher'),
(50, 'Sarah Foster', 'Computer Science Teacher'),
(51, 'Jason Ross', 'Physics Teacher'),
(52, 'Amanda Hernandez', 'Spanish Teacher'),
(53, 'Matthew Brooks', 'Mathematics Teacher'),
(54, 'Laura Reed', 'English Teacher'),
(55, 'Steven Turner', 'Science Teacher'),
(56, 'Natalie White', 'History Teacher'),
(57, 'Daniel Carter', 'Physical Education Teacher'),
(58, 'Sarah Evans', 'Art Teacher'),
(59, 'Michael Hill', 'Music Teacher'),
(60, 'Emily Collins', 'Computer Science Teacher'),
(61, 'Joshua Davis', 'Biology Teacher'),
(62, 'Stephanie Adams', 'Chemistry Teacher'),
(63, 'Robert Johnson', 'Geography Teacher'),
(64, 'Melissa Moore', 'Drama Teacher'),
(65, 'Christopher Bell', 'Mathematics Teacher'),
(66, 'Rebecca Torres', 'English Teacher'),
(67, 'Andrew Garcia', 'Science Teacher'),
(68, 'Jennifer Martin', 'History Teacher'),
(69, 'David Rodriguez', 'Physical Education Teacher'),
(70, 'Ashley Thompson', 'Art Teacher'),
(71, 'Joseph Wright', 'Music Teacher'),
(72, 'Katherine Turner', 'Computer Science Teacher'),
(73, 'Richard Harris', 'Physics Teacher'),
(74, 'Amy Clark', 'Spanish Teacher'),
(75, 'Daniel Young', 'Biology Teacher'),
(76, 'Samantha Phillips', 'Chemistry Teacher'),
(77, 'John Wilson', 'Geography Teacher'),
(78, 'Emily Lee', 'Drama Teacher'),
(79, 'David Anderson', 'Mathematics Teacher'),
(80, 'Amanda King', 'English Teacher'),
(81, 'Marcus Scott', 'Science Teacher'),
(82, 'Lauren Hall', 'History Teacher'),
(83, 'Brandon Adams', 'Physical Education Teacher'),
(84, 'Megan Taylor', 'Art Teacher'),
(85, 'Matthew Green', 'Music Teacher'),
(86, 'Olivia Martinez', 'Computer Science Teacher'),
(87, 'Michael Turner', 'Physics Teacher'),
(88, 'Sarah Collins', 'Spanish Teacher'),
(89, 'Jonathan Reed', 'Biology Teacher'),
(90, 'Stephanie Carter', 'Chemistry Teacher'),
(91, 'Thomas Wood', 'Geography Teacher'),
(92, 'Jessica Brown', 'Drama Teacher'),
(93, 'Joseph Perez', 'Mathematics Teacher'),
(94, 'Melissa Wilson', 'English Teacher'),
(95, 'Steven Harris', 'Science Teacher'),
(96, 'Natalie Turner', 'History Teacher'),
(97, 'Brian Moore', 'Physical Education Teacher'),
(98, 'Michelle Ward', 'Art Teacher'),
(99, 'James Turner', 'Music Teacher'),
(100, 'Emily Foster', 'Computer Science Teacher');