SELECT * FROM project_itc_cinema_system.movie;
SELECT * FROM Movie;

INSERT INTO Movie (theaterID, movieName, movieType, movieReleaseDate, movieDuration, movieRating, movieDescription)
VALUES
(2, 'The Avengers', 'Action', '2020-05-22', '02:30:00', 8.5, "Earth's mightiest heroes team up to save the world."),
(1, 'Titanic', 'Romance', '1997-12-19', '03:15:00', 7.8, 'A tragic love story set aboard the RMS Titanic.'),
(3, 'Inception', 'Sci-Fi', '2010-07-16', '02:28:00', 8.8, "A thief enters people's dreams to steal information."),
(2, 'The Lion King', 'Animation', '1994-06-24', '01:29:00', 8.5, 'A young lion prince must reclaim his throne.'),
(1, 'The Dark Knight', 'Action', '2008-07-18', '02:32:00', 9.0, 'Batman faces off against the Joker.'),
(2, 'Frozen', 'Animation', '2013-11-27', '01:42:00', 7.5, 'A fearless princess sets off on a journey to find her estranged sister.'),
(2, 'Jurassic Park', 'Adventure', '1993-06-11', '02:07:00', 8.1, 'Scientists create a theme park with genetically engineered dinosaurs.'),
(1, 'Avatar', 'Sci-Fi', '2009-12-18', '02:42:00', 7.8, 'A paralyzed marine is sent to the planet Pandora on a unique mission.'),
(1, 'Finding Nemo', 'Animation', '2003-05-30', '01:40:00', 8.1, 'A clownfish embarks on a journey to find his son.'),
(2,'Pulp Fiction', 'Crime', '1994-10-14', '02:34:00', 8.9, 'Interconnected stories of criminals in Los Angeles.'),
(1,'The Shawshank Redemption', 'Drama', '1994-09-23', '02:22:00', 9.3, 'Two imprisoned men bond over several years, finding solace and redemption through acts of common decency.'),
(1,'Interstellar', 'Sci-Fi', '2014-11-07', '02:49:00', 8.6, 'A group of explorers travel through a wormhole in space.'),
(2,'The Godfather', 'Crime', '1972-03-24', '02:55:00', 9.2, 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.'),
(2,'The Matrix', 'Sci-Fi', '1999-03-31', '02:16:00', 8.7, 'A computer hacker learns about the true nature of his reality.'),
(3, 'Forrest Gump', 'Drama', '1994-07-06', '02:22:00', 8.8, 'A simple man experiences firsthand some of the key events of the latter half of the 20th century.'),
(1, 'The Lord of the Rings: The Fellowship of the Ring', 'Fantasy', '2001-12-19', '02:58:00', 8.8, 'A hobbit sets out on a journey to destroy a powerful ring.'),
(3, 'Toy Story', 'Animation', '1995-11-22', '01:21:00', 8.3, 'Toys come to life when humans are not present.'),
(4, 'Inglourious Basterds', 'War', '2009-08-21', '02:33:00', 8.3, 'A group of Jewish U.S. soldiers plan to assassinate Nazi leaders in World War II.'),
(4, 'The Avengers: Endgame', 'Action', '2019-04-26', '03:01:00', 8.4, 'The Avengers assemble for one final showdown against Thanos.'),
(4, 'The Social Network', 'Drama', '2010-10-01', '02:00:00', 7.7, 'The story of the creation of Facebook.'),
(1, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman seeks revenge after being left for dead by his hunting team.'),
(2, 'The Great Gatsby', 'Drama', '2013-05-10', '02:23:00', 7.2, 'A writer becomes entangled in the world of the wealthy elite.'),
(3, 'La La Land', 'Musical', '2016-12-09', '02:08:00', 8.0, 'A jazz pianist falls in love with an aspiring actress in Los Angeles.'),
(4, 'The Hangover', 'Comedy', '2009-06-05', '01:40:00', 7.7, 'A group of friends search for their missing friend after a wild bachelor party in Las Vegas.'),
(2, 'Black Panther', 'Action', '2018-02-16', '02:14:00', 7.3, 'Challa, the Black Panther, rises to the throne of Wakanda.'),
(2, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'The true story of Jordan Belfort, a wealthy stockbroker involved in corruption and fraud.'),
(2, 'The Shape of Water', 'Fantasy', '2017-12-01', '02:03:00', 7.3, 'A mute janitor forms a unique relationship with an amphibious creature.'),
(2, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'A man becomes the prime suspect in his wife disappearance.'),
(2, 'The Fault in Our Stars', 'Romance', '2014-06-06', '02:06:00', 7.7, 'Two teenagers with cancer fall in love.'),
(3, 'The Pursuit of Happyness', 'Drama', '2006-12-15', '01:57:00', 8.0, 'A struggling salesman takes custody of his son as he embarks on a life-changing journey.'),
(3, 'The Martian', 'Sci-Fi', '2015-10-02', '02:24:00', 8.0, 'An astronaut is left stranded on Mars and must find a way to survive.'),
(3, 'The Conjuring', 'Horror', '2013-07-19', '01:52:00', 7.5, 'Paranormal investigators help a family terrorized by a dark presence in their farmhouse.'),
(3, 'The Notebook', 'Romance', '2004-06-25', '02:03:00', 7.8, 'A young couples love is tested by the pressures of society and war.'),
(4, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler.'),
(3, 'The Dark Knight Rises', 'Action', '2012-07-20', '02:44:00', 8.4, 'Batman returns to protect Gotham City from a new threat.'),
(1, 'The Shining', 'Horror', '1980-05-23', '02:26:00', 8.4, 'A family heads to an isolated hotel for the winter where an evil presence influences the father.'),
(2, 'Pulp Fiction', 'Crime', '1994-10-14', '02:34:00', 8.9, 'The lives of various characters intertwine in a world of crime and redemption.'),
(1, 'Interstellar', 'Sci-Fi', '2014-11-07', '02:49:00', 8.6, 'A team of explorers travel through a wormhole in search of a new habitable planet.'),
(4, 'The Matrix', 'Sci-Fi', '1999-03-31', '02:16:00', 8.7, 'A computer hacker learns the truth about his reality and his role in the war against machines.'),
(1, 'The Lion King', 'Animation', '1994-06-15', '01:28:00', 8.5, 'A young lion prince must reclaim his throne after his father murder.')
;

# ====================================================================================================================
INSERT INTO Movie (theaterID, movieName, movieType, movieReleaseDate, movieDuration, movieRating, movieDescription)
VALUES
(1, 'The Dark Knight Rises', 'Action', '2012-07-20', '02:44:00', 8.4, 'Batman returns to protect Gotham City from a new threat.'),
(3, 'The Pursuit of Happyness', 'Drama', '2006-12-15', '01:57:00', 8.0, 'A struggling salesman takes custody of his son as he embarks on a life-changing journey.'),
(4, 'The Martian', 'Sci-Fi', '2015-10-02', '02:24:00', 8.0, 'An astronaut is left stranded on Mars and must find a way to survive.'),
(2, 'The Conjuring', 'Horror', '2013-07-19', '01:52:00', 7.5, 'Paranormal investigators help a family terrorized by a dark presence in their farmhouse.'),
(3, 'The Notebook', 'Romance', '2004-06-25', '02:03:00', 7.8, 'A young couple\'s love is tested by the pressures of society and war.'),
(4, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler.'),
(3, 'The Dark Knight Rises', 'Action', '2012-07-20', '02:44:00', 8.4, 'Batman returns to protect Gotham City from a new threat.'),
(1, 'The Shining', 'Horror', '1980-05-23', '02:26:00', 8.4, 'A family heads to an isolated hotel for the winter where an evil presence influences the father.'),
(2, 'Pulp Fiction', 'Crime', '1994-10-14', '02:34:00', 8.9, 'The lives of various characters intertwine in a world of crime and redemption.'),
(1, 'Interstellar', 'Sci-Fi', '2014-11-07', '02:49:00', 8.6, 'A team of explorers travel through a wormhole in search of a new habitable planet.'),
(4, 'The Matrix', 'Sci-Fi', '1999-03-31', '02:16:00', 8.7, 'A computer hacker learns the truth about his reality and his role in the war against machines.'),
(1, 'The Lion King', 'Animation', '1994-06-15', '01:28:00', 8.5, 'A young lion prince must reclaim his throne after his father\'s murder.'),
(2, 'The Avengers', 'Action', '2012-05-04', '02:23:00', 8.0, 'Earth\'s mightiest heroes come together to battle a powerful enemy.'),
(3, 'Fight Club', 'Drama', '1999-10-15', '02:19:00', 8.8, 'An insomniac office worker forms an underground fight club as a form of therapy.'),
(4, 'The Godfather: Part II', 'Crime', '1974-12-20', '03:22:00', 9.0, 'The sequel continues the saga of the Corleone crime family.'),
(1, 'The Lord of the Rings: The Two Towers', 'Fantasy', '2002-12-18', '02:59:00', 8.7, 'The second installment of the epic fantasy trilogy.'),
(2, 'The Dark Knight', 'Action', '2008-07-18', '02:32:00', 9.0, 'Batman faces off against the Joker in a battle for Gotham City.'),
(3, 'Inception', 'Sci-Fi', '2010-07-16', '02:28:00', 8.8, 'A thief enters people\'s dreams to steal information.'),
(4, 'The Shawshank Redemption', 'Drama', '1994-09-23', '02:22:00', 9.3, 'Two imprisoned men bond over several years, finding solace and redemption through acts of common decency.'),
(1, 'Gladiator', 'Action', '2000-05-05', '02:35:00', 8.5, 'A former Roman General seeks revenge in the gladiatorial arena.'),
(2, 'Forrest Gump', 'Drama', '1994-07-06', '02:22:00', 8.8, 'A simple man experiences firsthand some of the key events of the latter half of the 20th century.'),
(3, 'The Silence of the Lambs', 'Thriller', '1991-02-14', '01:58:00', 8.6, 'An FBI trainee seeks the help of a manipulative serial killer to catch another serial killer.'),
(4, 'The Green Mile', 'Drama', '1999-12-10', '03:09:00', 8.6, 'A death row corrections officer witnesses supernatural events.'),
(1, 'The Prestige', 'Mystery', '2006-10-20', '02:10:00', 8.5, 'Two rival magicians engage in a dangerous game of one-upmanship.'),
(2, 'The Sixth Sense', 'Thriller', '1999-08-06', '01:47:00', 8.1, 'A child psychologist tries to help a young boy who claims to see ghosts.'),
(3, 'The Departed', 'Crime', '2006-10-06', '02:31:00', 8.5, 'An undercover cop and a mole in the police attempt to identify each other.'),
(4, 'The Social Network', 'Biography', '2010-10-01', '02:00:00', 7.7, 'The story of the creation of Facebook.'),
(1, 'Braveheart', 'Biography', '1995-05-24', '02:58:00', 8.3, 'The story of Scottish warrior William Wallace.'),
(2, 'The Exorcist', 'Horror', '1973-12-26', '02:02:00', 8.0, 'A young girl is possessed by a demonic entity, and her mother seeks help from two priests.'),
(3, 'The Lion King', 'Animation', '2019-07-19', '01:58:00', 7.9, 'A live-action remake of the Disney animated classic.'),
(4, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman seeks revenge after being left for dead by his hunting team.'),
(1, 'The Great Gatsby', 'Drama', '2013-05-10', '02:23:00', 7.2, 'A mysterious millionaire hosts extravagant parties in 1920s New York.'),
(2, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'The rise and fall of a wealthy stockbroker.'),
(3, 'The Imitation Game', 'Biography', '2014-11-28', '01:54:00', 8.0, 'The story of Alan Turing, the mathematician who helped crack the Enigma code during World War II.'),
(4, 'The Hangover', 'Comedy', '2009-06-05', '01:40:00', 7.7, 'A bachelor party in Las Vegas takes a wild and unexpected turn.'),
(1, 'The Conjuring 2', 'Horror', '2016-06-10', '02:14:00', 7.3, 'Paranormal investigators return to help a single mother and her four children.'),
(2, 'The Matrix Reloaded', 'Sci-Fi', '2003-05-15', '02:18:00', 7.2, 'Neo continues his quest for the truth in a simulated reality.'),
(3, 'The Bourne Identity', 'Action', '2002-06-14', '01:59:00', 7.9, 'A man is found floating in the Mediterranean Sea with no memory and a set of skills.'),
(4, 'The Hangover Part II', 'Comedy', '2011-05-26', '01:42:00', 6.5, 'The Wolfpack finds themselves in another misadventure, this time in Bangkok.'),
(1, 'The Bourne Supremacy', 'Action', '2004-07-23', '01:48:00', 7.7, 'Jason Bourne is targeted by a CIA operation gone wrong.'),
(2, 'The Matrix Revolutions', 'Sci-Fi', '2003-11-05', '02:09:00', 6.7, 'The final chapter in the Matrix trilogy.'),
(3, 'The Bourne Ultimatum', 'Action', '2007-08-03', '01:55:00', 8.0, 'Jason Bourne seeks to uncover his past while evading government agents.'),
(4, 'The Hangover Part III', 'Comedy', '2013-05-23', '01:40:00', 5.8, 'The Wolfpack returns to Las Vegas for one last outrageous adventure.'),
(1, 'The Conjuring: The Devil Made Me Do It', 'Horror', '2021-06-04', '01:51:00', 6.3, 'The Warrens investigate a murder case involving demonic possession.'),
(2, 'The Hobbit: An Unexpected Journey', 'Fantasy', '2012-12-14', '02:49:00', 7.8, 'Bilbo Baggins joins a quest to reclaim a dwarf kingdom from a fearsome dragon.'),
(3, 'The Girl with the Dragon Tattoo', 'Crime', '2011-12-20', '02:38:00', 7.8, 'A journalist and a hacker investigate a wealthy family\'s dark secrets.'),
(4, 'The Hangover Part III', 'Comedy', '2013-05-23', '01:40:00', 5.8, 'The Wolfpack returns to Las Vegas for one last outrageous adventure.'),
(1, 'The Conjuring: The Devil Made Me Do It', 'Horror', '2021-06-04', '01:51:00', 6.3, 'The Warrens investigate a murder case involving demonic possession.'),
(2, 'The Hobbit: An Unexpected Journey', 'Fantasy', '2012-12-14', '02:49:00', 7.8, 'Bilbo Baggins joins a quest to reclaim a dwarf kingdom from a fearsome dragon.'),
(3, 'The Girl with the Dragon Tattoo', 'Crime', '2011-12-20', '02:38:00', 7.8, 'A journalist and a hacker investigate a wealthy family\'s dark secrets.'),
(4, 'The Social Network', 'Biography', '2010-10-01', '02:00:00', 7.7, 'The story of the creation of Facebook.'),
(1, 'Braveheart', 'Biography', '1995-05-24', '02:58:00', 8.3, 'The story of Scottish warrior William Wallace.'),
(2, 'The Exorcist', 'Horror', '1973-12-26', '02:02:00', 8.0, 'A young girl is possessed by a demonic entity, and her mother seeks help from two priests.'),
(3, 'The Lion King', 'Animation', '2019-07-19', '01:58:00', 7.9, 'A live-action remake of the Disney animated classic.'),
(4, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman seeks revenge after being left for dead by his hunting team.'),
(1, 'The Great Gatsby', 'Drama', '2013-05-10', '02:23:00', 7.2, 'A mysterious millionaire hosts extravagant parties in 1920s New York.'),
(2, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'The rise and fall of a wealthy stockbroker.'),
(3, 'The Imitation Game', 'Biography', '2014-11-28', '01:54:00', 8.0, 'The story of Alan Turing, the mathematician who helped crack the Enigma code during World War II.'),
(4, 'The Hangover', 'Comedy', '2009-06-05', '01:40:00', 7.7, 'A bachelor party in Las Vegas takes a wild and unexpected turn.'),
(1, 'The Conjuring 2', 'Horror', '2016-06-10', '02:14:00', 7.3, 'Paranormal investigators return to help a single mother and her four children.'),
(2, 'The Matrix Reloaded', 'Sci-Fi', '2003-05-15', '02:18:00', 7.2, 'Neo continues his quest for the truth in a simulated reality.'),
(3, 'The Bourne Identity', 'Action', '2002-06-14', '01:59:00', 7.9, 'A man is found floating in the Mediterranean Sea with no memory and a set of skills.'),
(4, 'The Hangover Part II', 'Comedy', '2011-05-26', '01:42:00', 6.5, 'The Wolfpack finds themselves in another misadventure, this time in Bangkok.'),
(1, 'The Bourne Supremacy', 'Action', '2004-07-23', '01:48:00', 7.7, 'Jason Bourne is targeted by a CIA operation gone wrong.'),
(2, 'The Matrix Revolutions', 'Sci-Fi', '2003-11-05', '02:09:00', 6.7, 'The final chapter in the Matrix trilogy.'),
(3, 'The Bourne Ultimatum', 'Action', '2007-08-03', '01:55:00', 8.0, 'Jason Bourne seeks to uncover his past while evading government agents.'),
(4, 'The Hangover Part III', 'Comedy', '2013-05-23', '01:40:00', 5.8, 'The Wolfpack returns to Las Vegas for one last outrageous adventure.'),
(1, 'The Conjuring: The Devil Made Me Do It', 'Horror', '2021-06-04', '01:51:00', 6.3, 'The Warrens investigate a murder case involving demonic possession.'),
(2, 'The Hobbit: An Unexpected Journey', 'Fantasy', '2012-12-14', '02:49:00', 7.8, 'Bilbo Baggins joins a quest to reclaim a dwarf kingdom from a fearsome dragon.'),
(3, 'The Girl with the Dragon Tattoo', 'Crime', '2011-12-20', '02:38:00', 7.8, 'A journalist and a hacker investigate a wealthy family\'s dark secrets.'),
(4, 'The Hangover Part III', 'Comedy', '2013-05-23', '01:40:00', 5.8, 'The Wolfpack returns to Las Vegas for one last outrageous adventure.')
;


INSERT INTO Movie (theaterID, movieName, movieType, movieReleaseDate, movieDuration, movieRating, movieDescription)
VALUES
(1, 'Spider-Man: Homecoming', 'Action', '2017-07-07', '02:13:00', 7.4, 'Peter Parker balances his life as a high school student and a web-slinging superhero.'),
(2, 'The Godfather: Part II', 'Crime', '1974-12-18', '03:22:00', 9.0, 'The saga of the Corleone family continues as a young Vito Corleone expands his empire.'),
(3, 'The Dark Knight Rises', 'Action', '2012-07-20', '02:44:00', 8.4, 'Batman returns to protect Gotham City from a new threat.'),
(4, 'The Shawshank Redemption', 'Drama', '1994-09-23', '02:22:00', 9.3, 'Two imprisoned men bond over several years, finding solace and redemption through acts of common decency.'),
(1, 'Guardians of the Galaxy', 'Action', '2014-08-01', '02:01:00', 8.0, 'A group of intergalactic misfits join forces to save the galaxy.'),
(2, 'The Lord of the Rings: The Two Towers', 'Fantasy', '2002-12-18', '02:59:00', 8.7, 'The Fellowship divides as Frodo and Sam continue their journey to Mount Doom.'),
(3, 'The Lion King', 'Animation', '1994-06-24', '01:29:00', 8.5, 'A young lion prince must reclaim his throne.'),
(4, 'Fight Club', 'Drama', '1999-10-15', '02:19:00', 8.8, 'An insomniac office worker and a soap salesman form an underground fight club.'),
(1, 'The Avengers', 'Action', '2012-05-04', '02:23:00', 8.0, 'Earth\'s mightiest heroes assemble to save the world from a powerful threat.'),
(2, 'The Matrix', 'Sci-Fi', '1999-03-31', '02:16:00', 8.7, 'A computer hacker learns about the true nature of his reality.'),
(3, 'Pulp Fiction', 'Crime', '1994-10-14', '02:34:00', 8.9, 'Interconnected stories of criminals in Los Angeles.'),
(4, 'Forrest Gump', 'Drama', '1994-07-06', '02:22:00', 8.8, 'A simple man experiences firsthand some of the key events of the latter half of the 20th century.'),
(1, 'The Dark Knight', 'Action', '2008-07-18', '02:32:00', 9.0, 'Batman faces off against the Joker.'),
(2, 'Inception', 'Sci-Fi', '2010-07-16', '02:28:00', 8.8, 'A thief enters people\'s dreams to steal information.'),
(3, 'Schindler\'s List', 'Biography', '1993-11-30', '03:15:00', 8.9, 'A German businessman saves the lives of more than a thousand Jewish refugees during World War II.'),
(4, 'The Green Mile', 'Crime', '1999-12-10', '03:09:00', 8.6, 'The lives of guards on Death Row are affected by a convicted prisoner with a mysterious gift.'),
(1, 'The Lord of the Rings: The Return of the King', 'Fantasy', '2003-12-17', '03:21:00', 8.9, 'The final battle for Middle-earth begins as Frodo and Sam continue their quest to destroy the One Ring.'),
(2, 'The Departed', 'Crime', '2006-10-06', '02:31:00', 8.5, 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.'),
(3, 'The Silence of the Lambs', 'Crime', '1991-02-14', '01:58:00', 8.6, 'A young FBI cadet seeks the help of an incarcerated and manipulative cannibal killer to catch another serial killer.'),
(4, 'Goodfellas', 'Crime', '1990-09-19', '02:25:00', 8.7, 'The rise and fall of a mob associate in the world of organized crime.'),
(1, 'The Prestige', 'Drama', '2006-10-20', '02:10:00', 8.5, 'Two magicians engage in a battle to create the ultimate stage illusion.'),
(2, 'Back to the Future', 'Adventure', '1985-07-03', '01:56:00', 8.5, 'A teenager is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his eccentric scientist friend.'),
(3, 'Gladiator', 'Action', '2000-05-05', '02:35:00', 8.5, 'A former Roman General seeks vengeance against the corrupt emperor who murdered his family.'),
(4, 'The Lion King', 'Animation', '1994-06-15', '01:28:00', 8.5, 'A young lion prince must reclaim his throne after his father\'s murder.'),
(1, 'The Notebook', 'Romance', '2004-06-25', '02:03:00', 7.8, 'A young couple\'s love is tested by the pressures of society and war.'),
(2, 'Jurassic Park', 'Adventure', '1993-06-11', '02:07:00', 8.1, 'Scientists create a theme park with genetically engineered dinosaurs.'),
(3, 'Schindler\'s List', 'Biography', '1993-11-30', '03:15:00', 8.9, 'A German businessman saves the lives of more than a thousand Jewish refugees during World War II.'),
(4, 'The Social Network', 'Drama', '2010-10-01', '02:00:00', 7.7, 'The story of the creation of Facebook.'),
(1, 'The Fault in Our Stars', 'Romance', '2014-06-06', '02:06:00', 7.7, 'Two teenagers with cancer fall in love.'),
(2, 'The Pursuit of Happyness', 'Drama', '2006-12-15', '01:57:00', 8.0, 'A struggling salesman takes custody of his son as he embarks on a life-changing journey.'),
(3, 'The Martian', 'Sci-Fi', '2015-10-02', '02:24:00', 8.0, 'An astronaut is left stranded on Mars and must find a way to survive.'),
(4, 'Inglourious Basterds', 'Adventure', '2009-08-21', '02:33:00', 8.3, 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans.'),
(1, 'The Matrix', 'Sci-Fi', '1999-03-31', '02:16:00', 8.7, 'A computer hacker learns about the true nature of his reality.'),
(2, 'Interstellar', 'Sci-Fi', '2014-11-07', '02:49:00', 8.6, 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.'),
(3, 'Whiplash', 'Drama', '2014-10-15', '01:46:00', 8.5, 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.'),
(4, 'The Grand Budapest Hotel', 'Adventure', '2014-03-28', '01:39:00', 8.1, 'The adventures of a legendary concierge at a famous European hotel between the wars.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.'),
(3, 'The Wolf of Wall Street', 'Biography', '2013-12-25', '03:00:00', 8.2, 'Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker to his fall involving crime, corruption, and the federal government.'),
(4, 'Gone Girl', 'Mystery', '2014-10-03', '02:29:00', 8.1, 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.'),
(1, 'Avengers: Infinity War', 'Action', '2018-04-27', '02:29:00', 8.4, 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.'),
(2, 'Birdman or (The Unexpected Virtue of Ignorance)', 'Drama', '2014-11-14', '01:59:00', 7.7, 'A washed-up superhero actor attempts to revive his fading career by writing, directing, and starring in a Broadway production.'),
(3, 'The Big Short', 'Biography', '2015-12-23', '02:10:00', 7.8, 'In 2006-2007, a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.'),
(4, 'Spotlight', 'Biography', '2015-11-20', '02:09:00', 8.1, 'The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese.'),
(1, 'Black Swan', 'Drama', '2010-12-17', '01:48:00', 8.0, 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan - Princess Odette - but slowly loses her mind as she becomes more and more like Odile, the Black Swan.'),
(2, 'Mad Max: Fury Road', 'Action', '2015-05-15', '02:00:00', 8.1, 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.'),
(3, 'The Imitation Game', 'Biography', '2014-11-14', '01:54:00', 8.0, 'During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.'),
(4, 'Her', 'Drama', '2013-12-18', '02:06:00', 8.0, 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.'),
(1, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(2, 'Moonlight', 'Drama', '2016-10-21', '01:51:00', 7.4, 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.'),
(3, 'Dunkirk', 'Action', '2017-07-21', '01:46:00', 7.8, 'Allied soldiers from Belgium, the British Empire, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'),
(4, 'The Shape of Water', 'Adventure', '2017-12-22', '02:03:00', 7.3, 'At a top-secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.'),
(1, 'La La Land', 'Drama', '2016-12-25', '02:08:00', 8.0, 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.'),
(2, 'The Revenant', 'Adventure', '2015-12-25', '02:36:00', 8.0, 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.')
;





















