INSERT INTO authors VALUES (1, 'William Dea', 'Howells');
INSERT INTO authors VALUES (2, 'Frederic', 'Brow');
INSERT INTO authors VALUES (3, 'Jack', 'Londo');
INSERT INTO authors VALUES (4, 'Albert', 'Blaisdell');
INSERT INTO authors VALUES (5, 'Ellis', 'Butler');
INSERT INTO authors VALUES (6, 'Arthur', 'Mache');
INSERT INTO authors VALUES (7, 'Titus', 'Lucretius');
INSERT INTO authors VALUES (8, 'Rabindranath', 'Tare');
INSERT INTO authors VALUES (9, 'Isaac', 'Asimov');
INSERT INTO authors VALUES (10, 'Charles', 'Dickens');
INSERT INTO authors VALUES (11, 'Ralph Waldo', 'Emerso');
INSERT INTO authors VALUES (12, 'Dorothy', 'Canfield');
INSERT INTO authors VALUES (13, 'Givoanni', 'Boccaccio');
INSERT INTO authors VALUES (14, 'George', 'Orwell');
INSERT INTO authors VALUES (15, 'Publius', 'Ovid');
INSERT INTO authors VALUES (16, 'Robert Louis', 'Stevenso');
INSERT INTO authors VALUES (17, 'Virginia', 'Woolf');
INSERT INTO authors VALUES (18, 'George', 'Eliot');
INSERT INTO authors VALUES (19, 'Amelia B.', 'Edwards');
INSERT INTO authors VALUES (20, 'Fyodor', 'Dostoevsky');
INSERT INTO authors VALUES (21, 'Emily', 'Dickinso');
INSERT INTO authors VALUES (22, 'Edna', 'Ferber');
INSERT INTO authors VALUES (23, 'Joseph Sherida', 'LeFanu');
INSERT INTO authors VALUES (24, 'Joh', 'DosPassos');
INSERT INTO authors VALUES (25, 'Ruth', 'Stuart');
INSERT INTO authors VALUES (26, 'Vladimir', 'Nabokov');
INSERT INTO authors VALUES (27, 'Johanna', 'Spyri');
INSERT INTO authors VALUES (28, 'Ernest', 'Dowso');
INSERT INTO authors VALUES (29, 'Mary Hallock', 'Foote');
INSERT INTO authors VALUES (30, 'Zane', 'Grey');
INSERT INTO authors VALUES (31, 'H. P.', 'Lovecraft');
INSERT INTO authors VALUES (32, 'Samuel', 'Pepys');
INSERT INTO authors VALUES (33, 'Kate Dickinso', 'Sweetser');
INSERT INTO authors VALUES (34, 'William', 'Lampto');
INSERT INTO authors VALUES (35, 'Mother', 'ose');
INSERT INTO authors VALUES (36, 'Eleanor Hallowell', 'Abbott');