INSERT INTO types VALUES (1, 'Science fictio');
INSERT INTO types VALUES (2, 'Satire');
INSERT INTO types VALUES (3, 'Drama');
INSERT INTO types VALUES (4, 'Action and Adventure');
INSERT INTO types VALUES (5, 'Romance');
INSERT INTO types VALUES (6, 'Mystery');
INSERT INTO types VALUES (7, 'Horror');
INSERT INTO types VALUES (8, 'Health');
INSERT INTO types VALUES (9, 'Guide');
INSERT INTO types VALUES (10, 'Diaries');
INSERT INTO types VALUES (11, 'Comics');
INSERT INTO types VALUES (12, 'Diaries');
INSERT INTO types VALUES (13, 'Journals');
INSERT INTO types VALUES (14, 'Biographies');
INSERT INTO types VALUES (15, 'Fantasy');
INSERT INTO types VALUES (16, 'History');
INSERT INTO types VALUES (17, 'Science');
INSERT INTO types VALUES (18, 'Art');